apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyso-api-deployment
  labels:
    app: kyso-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyso-api
  template:
    metadata:
      labels:
        app: kyso-api
    spec:
      containers:
        - name: kyso-api
          image: fjbarrena/kyso-api:latest
          env:
            - name: CLUSTER_NAMESPACE
              value: default
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: secret
            - name: MONGO_HOST
              value: mongodb-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_PATH
              value: admin
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8050
          resources:
            limits:
              memory: "800M"
              cpu: "0.4"
          volumeMounts:
            - name: config
              mountPath: "/opt/kyso/api/kube"
              readOnly: true
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: kyso-environment-configmap
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "kube-config"
              path: "kube-config"
---
apiVersion: v1
kind: Service
metadata:
  name: kyso-api-service
  labels:
    app: kyso-api
spec:
  type: NodePort
  selector:
    app: kyso-api
  ports:
    - protocol: TCP
      name: web
      port: 8050
