apiVersion: v1
kind: Service
metadata:
  name: kyso-dash-service-#RANDOMIZE
  labels:
    app: kyso-dash
spec:
  type: NodePort
  selector:
    app: kyso-dash
  ports:
    - protocol: TCP
      name: web
      port: 8050
